/**
 * @file    Timer.c
 * @brief   Lesson 6-1: TIM2 Timer Interrupt
 * @note    Configures TIM2 for periodic interrupt every 10ms
 *
 * Timer Configuration:
 *   - APB1 Clock: 72MHz
 *   - Prescaler (PSC): 7200-1
 *   - Auto-Reload (ARR): 10000-1
 *   - Interrupt Period: (7200 * 10000) / 72000000 = 1 second
 *
 * Hardware: No external connections needed (internal timer)
 */

#include "stm32f10x.h"
#include "Timer.h"

uint16_t Num = 0;  // Variable incremented in timer interrupt

/**
 * @brief  Initialize TIM2 for periodic interrupt
 * @note   Uses internal clock, generates interrupt every 1 second
 */
void Timer_Init(void)
{
    /* Enable TIM2 clock */
    RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM2, ENABLE);

    /* Configure time base unit */
    TIM_TimeBaseInitTypeDef TIM_TimeBaseInitStructure;
    TIM_TimeBaseInitStructure.TIM_ClockDivision = TIM_CKD_DIV1;
    TIM_TimeBaseInitStructure.TIM_CounterMode = TIM_CounterMode_Up;
    TIM_TimeBaseInitStructure.TIM_Period = 10000 - 1;      // ARR = 10000
    TIM_TimeBaseInitStructure.TIM_Prescaler = 7200 - 1;    // PSC = 7200
    TIM_TimeBaseInitStructure.TIM_RepetitionCounter = 0;
    TIM_TimeBaseInit(TIM2, &TIM_TimeBaseInitStructure);

    /* Clear update flag (generated by Init function) */
    TIM_ClearFlag(TIM2, TIM_FLAG_Update);

    /* Enable update interrupt */
    TIM_ITConfig(TIM2, TIM_IT_Update, ENABLE);

    /* NVIC configuration */
    NVIC_PriorityGroupConfig(NVIC_PriorityGroup_2);
    NVIC_InitTypeDef NVIC_InitStructure;
    NVIC_InitStructure.NVIC_IRQChannel = TIM2_IRQn;
    NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
    NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 2;
    NVIC_InitStructure.NVIC_IRQChannelSubPriority = 1;
    NVIC_Init(&NVIC_InitStructure);

    /* Enable TIM2 */
    TIM_Cmd(TIM2, ENABLE);
}

/**
 * @brief  TIM2 Interrupt Handler
 * @note   Called automatically every 1 second
 */
void TIM2_IRQHandler(void)
{
    if (TIM_GetITStatus(TIM2, TIM_IT_Update) == SET)
    {
        Num++;  // Increment counter
        TIM_ClearITPendingBit(TIM2, TIM_IT_Update);  // Clear interrupt flag
    }
}
